# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
       #     pattern: ^/aa
       #     form_login:
       #         provider: fos_userbundle
       #         csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
       #     logout:       true
       #     anonymous:    true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            security:   false

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false



        default:
            anonymous: ~
            http_basic: ~


    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/reg, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
