# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders: #dodane
            AppBundle\Entity\User:
                algorithm: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default: #dołożone
            anonymous: ~
            http_basic: ~

    access_control: #dołożone
        - {path: ^/admin, roles: ROLE_ADMIN }

        #main: #domyślnie dobre
            #anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
